fix flashing error message on send name modal
ensdomains/ens-app-v3 pull request #228
Opened 2022-11-21 05:39 UTC by storywithoutend

2022-11-23 07:11 UTC, TateB requested changes

2022-11-23 07:11 UTC, TateB commented on src/components/@molecules/TransactionDialogManager/TransactionDialogManager.tsx
> +    <Dialog variant="blank" open={!!selectedKey} onDismiss={onBackgroundDismiss}>
pretty sure it was previously `state.selectedKey` to make sure that that dismiss animation is finished before unloading the modal

2022-11-23 07:11 UTC, TateB commented on src/hooks/useBasicName.ts
> +    async () => {
this func doesn't need to be async since a promise is returned either way

2022-11-23 07:11 UTC, TateB commented on src/hooks/useBasicName.ts
> +      const batchQueries = await addRegistrationStatusToBatch(ens, normalisedName)
this func isn't async, await won't do anything

2022-11-28 08:12 UTC, LeonmanRolls approved these changes

2022-11-29 02:04 UTC, merged