Eng659 improved registration
ensdomains/ens-app-v3 pull request #260
Opened 2022-12-15 16:12 UTC by storywithoutend

2023-01-23 02:20 UTC, TateB requested changes
visual notes:
- add profile fields dialog
  - we might want to restrict the height of the dialog on desktop, seems too big
  - option buttons dont have hover state
  - sidebar doesn't look clickable
- there are no errors if any records are blank (esp. problematic for addresses),  is this intended?
- clear button doesn't appear until the input has a value, but then clicking it removes the entire record instead of just clearing the input. seems confusing to have a button that traditionally clears an input instead just delete it.
- DOT address record has a weird error
<img width="747" alt="Screenshot 2023-01-23 at 12 59 17 pm" src="https://user-images.githubusercontent.com/11844316/213954286-aa4ab3d8-2f8c-4cb1-a28e-ac089fe14442.png">

2023-01-23 02:20 UTC, TateB commented on src/assets/CrossCircle.svg
> +<svg width="120" height="120" viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg">
is this not in thorin?

2023-01-23 02:20 UTC, TateB commented on src/assets/Question.svg
> +<svg width="21" height="20" viewBox="0 0 21 20" fill="none" xmlns="http://www.w3.org/2000/svg">
same here

2023-01-23 02:20 UTC, TateB commented on src/assets/address/DynamicAddressIcon.tsx
> +    const Icon = dynamic(() => import('../Question.svg')) as any
not much point in making this a dynamic import

2023-01-23 02:20 UTC, TateB commented on src/components/pages/profile/[name]/registration/steps/Profile/AddProfileRecordView.tsx
> +  }, [debouncedSearch, t, i18n])
tbh not sure that this search needs to be debounced, feels awkward in the UI and not necessary since there's no external network reqs

2023-01-23 02:20 UTC, TateB commented on src/components/pages/profile/[name]/registration/steps/Profile/Profile.test.tsx
> +jest.mock('wagmi')
wagmi is mocked in `test-utils.tsx`

2023-01-23 02:20 UTC, TateB commented on src/components/pages/profile/[name]/registration/steps/Profile/ProfileRecordInput.tsx
> +            // }
delete

2023-01-23 02:20 UTC, TateB commented on src/components/pages/profile/[name]/registration/steps/Profile/WrappedAvatarButton.tsx
> +  console.log(props.src)
remove

2023-01-23 15:59 UTC, storywithoutend commented
> visual notes:
> 
> * add profile fields dialog
>   
>   * we might want to restrict the height of the dialog on desktop, seems too big

Set max height to 600px in desktop mode.

>   * option buttons dont have hover state

Add hover states

>   * sidebar doesn't look clickable

Copied the styling of tabs. 

> * there are no errors if any records are blank (esp. problematic for addresses),  is this intended?

I originally didn't think it was a big deal because since we are setting record it shouldn't be an issue, but now that you bring it up I do think it's better to keep convention throughout. 

> * clear button doesn't appear until the input has a value, but then clicking it removes the entire record instead of just clearing the input. seems confusing to have a button that traditionally clears an input instead just delete it.

Gonna run this by Dom. I do agree.

> * DOT address record has a weird error

These errors are the same errors produced by the token validation package. We could simplify them by turning them all into a single error such as "Invalid address"

> 
> <img alt="Screenshot 2023-01-23 at 12 59 17 pm" width="747" src="https://user-images.githubusercontent.com/11844316/213954286-aa4ab3d8-2f8c-4cb1-a28e-ac089fe14442.png">

2023-01-24 00:29 UTC, TateB commented
> These errors are the same errors produced by the token validation package. We could simplify them by turning them all into a single error such as "Invalid address"

makes sense to me

2023-01-26 10:01 UTC, merged