update set primary name flow [reset]
ensdomains/ens-app-v3 pull request #401
Opened 2023-04-05 06:25 UTC by storywithoutend

2023-04-17 00:30 UTC, TateB requested changes

2023-04-17 00:30 UTC, TateB commented on src/utils/utils.ts
> +}
nit: put this in its own file since its not very generic

2023-04-17 00:30 UTC, TateB commented on src/hooks/reverseRecord/useCanResolverSetPrimaryName.ts
> +    refetchOnMount: true,
what is this for?

2023-04-17 00:30 UTC, TateB commented on src/pages/my/settings.tsx
> +                  </Button>
null check on actionLabel means this button could have a blank label

2023-04-17 00:30 UTC, TateB commented on src/transaction-flow/input/SelectPrimaryName/SelectPrimaryName-flow.tsx
> +    }
is it worth trying to get the decoded label with `getDecryptedName()` from ensjs?

2023-04-17 00:30 UTC, TateB commented on src/transaction-flow/input/SelectPrimaryName/SelectPrimaryName-flow.tsx
> +          </Button>
maybe show the loading state for `onSubmit()` since its async?

2023-04-17 00:30 UTC, TateB commented on src/transaction-flow/input/SelectPrimaryName/SelectPrimaryName.test.tsx
> +describe('SelectPrimaryName', () => {
tests for `onSubmit()` variants? (e.g. 1 step set name, 2 step no matching eth, 3 step no valid resolver)

2023-04-17 03:22 UTC, storywithoutend commented on src/hooks/useGetRegistryResolver.ts
> +export const useGetRegistryResolver = (name: string) => {
update

2023-04-17 03:22 UTC, storywithoutend commented on src/components/pages/profile/[name]/tabs/MoreTab/Resolver.tsx
> +  // resolverAddress: universalResolverAddress,
switched back to showing wildcard name

2023-06-07 04:06 UTC, TateB requested changes

2023-06-07 05:35 UTC, storywithoutend commented on src/transaction-flow/input/UnknownLabels/UnknownLabels-flow.tsx
> +    queryClient.resetQueries(validateKey(newKey))
Replaced newKey with name

2023-06-07 05:45 UTC, storywithoutend commented on src/hooks/usePrimary.ts
> +        }
returning null breaks destructuring and changes the shape of the return data. A possible compromise is returning null as the values for name and beautified name.

2023-06-07 06:56 UTC, LeonmanRolls approved these changes

2023-06-15 05:20 UTC, LeonmanRolls commented on src/hooks/resolver/useResolverIsAuthorized.ts
> +  const resolverAddress = profile.profile?.resolverAddress ?? ''
Add check for 0x00

2023-06-15 05:26 UTC, LeonmanRolls commented on src/hooks/useProfileActions.ts
> +    const transactionFlowItem = getPrimaryNameTransactionFlowItem?.callBack?.(name)
should return null if there are actually no transactions

2023-06-15 05:33 UTC, LeonmanRolls approved these changes

2023-06-15 08:43 UTC, merged