Add Phantom Wallet
ensdomains/ens-app-v3 pull request #580
Opened 2023-08-29 04:22 UTC by LeonmanRolls

2023-08-29 23:34 UTC, TateB requested changes

2023-08-29 23:34 UTC, TateB commented on src/utils/getDefaultWallets.ts
> +        phantomWallet({ chains }),
move this to be with all the other injected wallets so it shows up first

2023-11-20 21:32 UTC, gskril approved these changes

2023-11-21 17:35 UTC, sugh01 approved these changes

2023-11-21 19:20 UTC, sugh01 requested changes
I was not able to complete registration with phantom wallet, needs retest.

2023-11-29 06:35 UTC, sugh01 approved these changes

2023-11-29 06:42 UTC, sugh01 approved these changes

2023-12-04 16:01 UTC, merged