feat: new dns import flow
ensdomains/ens-app-v3 pull request #621
Opened 2024-01-24 04:58 UTC by TateB

2024-02-13 18:23 UTC, sugh01 approved these changes

2024-02-14 07:00 UTC, storywithoutend requested changes

2024-02-14 07:26 UTC, TateB commented on src/components/pages/import/[name]/useDnsImportReducer.ts
> +
thx

2024-02-14 07:28 UTC, TateB commented on src/components/pages/import/[name]/useDnsImportReducer.ts
> +
void/undefined return for a reducer func is normal/expected behaviour, and is within the bounds of the type

2024-02-15 01:46 UTC, storywithoutend approved these changes

2024-02-15 02:01 UTC, merged