deal with long running transactions
ensdomains/ens-app-v3 pull request #701
Opened 2024-03-29 15:05 UTC by talentlessguy

![image](https://github.com/ensdomains/ens-app-v3/assets/35937217/aa4b9f3b-5c2a-4b8a-90ff-a5abd9e208d8)

To test, change `stage` to `sent` in `TransactionStageModal` so it will be stuck and you'll see a message

2024-04-01 02:43 UTC, storywithoutend requested changes

2024-04-01 02:43 UTC, storywithoutend commented on src/components/@molecules/TransactionDialogManager/stage/TransactionStageModal.tsx
> +        </Outlink>
add translation

2024-04-01 03:43 UTC, LeonmanRolls commented on src/components/@molecules/TransactionDialogManager/stage/TransactionStageModal.tsx
> +  const isTakingLongerThanExpected = status === 'sent' && progress === 100
Liking the readability improvement here

2024-04-01 03:44 UTC, LeonmanRolls approved these changes

2024-04-01 05:02 UTC, talentlessguy commented on src/components/@molecules/TransactionDialogManager/stage/TransactionStageModal.tsx
> +        </Outlink>
ok I'll move it to to locales

2024-04-04 13:53 UTC, sugh01 approved these changes

2024-04-04 14:46 UTC, merged