FET-1534
ensdomains/ens-app-v3 pull request #762
Opened 2024-07-15 15:05 UTC by yeewiz

- filtered out the primary name from the list of name addresses
- added unit test to test to make sure the primary name is not within the list

2024-07-15 16:22 UTC, storywithoutend requested changes
A small bug. When searching for the currentPrimaryname, the list area will be blank because the primary name is being filtered out, but the condition for showing the list of names has a length greater than 1.

2024-07-15 18:03 UTC, yeewiz commented on src/transaction-flow/input/SelectPrimaryName/SelectPrimaryName.test.tsx
> +      },
doh! changed it to be the same

2024-07-15 18:03 UTC, yeewiz commented
> A small bug. When searching for the currentPrimaryname, the list area will be blank because the primary name is being filtered out, but the condition for showing the list of names has a length greater than 1.

should be resolved now @storywithoutend

2024-07-15 18:14 UTC, storywithoutend approved these changes

2024-07-17 18:39 UTC, closed without merging

2024-07-17 18:47 UTC, yeewiz commented
didn't want reverts to effect the date branch changes so created new PR: https://github.com/ensdomains/ens-app-v3/pull/764