FET-1335: Make ETH record permanently visible when editing profile
ensdomains/ens-app-v3 pull request #781
Opened 2024-07-26 14:40 UTC by staslysak

2024-07-31 08:12 UTC, storywithoutend commented on src/components/pages/profile/[name]/registration/steps/Profile/profileRecordUtils.ts
> +
This causing a bug. It will delete any eth value if it exists in the previous record

2024-08-02 01:08 UTC, LeonmanRolls approved these changes

2024-08-02 04:48 UTC, storywithoutend requested changes

2024-08-02 04:48 UTC, storywithoutend commented on src/transaction-flow/input/ProfileEditor/ProfileEditor-flow.tsx
> +                      } else {
This is unnecessary since the field group is "custom" which means that it will always be a text record.

2024-08-02 04:48 UTC, storywithoutend commented on src/transaction-flow/input/ProfileEditor/ProfileEditor-flow.tsx
> +                      } else {
This is unnecessary since the key is "descriptions" which means it will be a <textarea/> tag. Which will never be an address.

2024-08-02 15:42 UTC, merged