Add Russian and Ukranian languages to the manager app
ensdomains/ens-app-v3 pull request #807
Opened 2024-08-09 10:34 UTC by staslysak

2024-08-14 12:04 UTC, LeonmanRolls approved these changes

2024-08-19 15:25 UTC, talentlessguy requested changes

2024-08-19 15:25 UTC, talentlessguy commented on public/locales/ru/dnssec.json
> +        },
```suggestion
          "description": "У вашего имени не будет токена на блокчейне.<br/>Это не влияет на его способность получать транзакции или возможностью пользоваться им в качестве основного имени.<br/><b>Вы не сможете редактировать свой профиль из ENS приложения.</b>"
        },
```

2024-08-19 15:25 UTC, talentlessguy commented on public/locales/ru/dnssec.json
> +          "description": "Ваше имя будет иметь токен в цепочке."
```suggestion
          "description": "У вашего имени будет токен на блокчейне."
```

2024-08-19 15:25 UTC, talentlessguy commented on public/locales/ru/dnssec.json
> +      "estimatedNetworkCost": "Оценочная стоимость сети"
```suggestion
      "estimatedNetworkCost": "Оценочная комиссия сети"
```

2024-08-19 15:25 UTC, talentlessguy commented on public/locales/ru/dnssec.json
> +        "description": "Этот домен был успешно импортирован в ENS. Теперь вы можете просмотреть это имя.",
```suggestion
        "description": "Домен был успешно импортирован в ENS. Теперь вы можете просмотреть его.",
```

2024-08-19 15:25 UTC, talentlessguy commented on public/locales/ru/error.json
> +    "message": "Произошла ошибка. <br /> Если это повторяющаяся проблема, пожалуйста, <SupportLink>посетите нашу поддержку</SupportLink> для получения дополнительной помощи."
```suggestion
    "message": "Произошла ошибка. <br /> Если проблема повторится, пожалуйста, <SupportLink>обратитесь в нашу поддержку</SupportLink> для получения дополнительной помощи."
```

2024-08-19 15:25 UTC, talentlessguy commented on public/locales/ru/names.json
> +    "text": "Офчейн-имена в настоящее время не отображаются в этом списке. Вы все равно можете просматривать их, ища их напрямую. Нажмите, чтобы узнать больше."
```suggestion
    "text": "Оффчейн-имена в настоящее время не отображаются в этом списке. Вы все равно можете просматривать их, ища их напрямую. Нажмите, чтобы узнать больше."
```

2024-08-19 15:25 UTC, talentlessguy commented on public/locales/ru/register.json
> +      "multipleYearsMessage": "Продление на несколько лет позволит сэкономить на сетевых расходах, избегая ежегодных транзакций.",
```suggestion
      "multipleYearsMessage": "Продление на несколько лет позволит сэкономить на комиссии блокчейна, избегая ежегодных транзакций.",
```

2024-08-19 15:25 UTC, talentlessguy commented on public/locales/ru/register.json
> +      "title": "Создайте свой профиль",
```suggestion
      "title": "Создание профиля",
```

2024-08-19 15:25 UTC, talentlessguy commented on public/locales/ru/register.json
> +              "name": "Псевдоним",
```suggestion
              "name": "Никнейм",
```

2024-08-19 15:25 UTC, talentlessguy commented on public/locales/ru/register.json
> +              "description": "Я фермер с доходов из сельской Теннесси."
```suggestion
              "description": "Я фермер из села в Теннесси."
```

2024-08-19 15:30 UTC, talentlessguy commented on public/locales/ru/dnssec.json
> +      "title": "Претендовать на {{name}}",
```suggestion
      "title": "Получить {{name}}",
```

2024-08-19 15:31 UTC, talentlessguy commented on public/locales/ru/dnssec.json
> +          "name": "Вне сети",
```suggestion
          "name": "Оффчейн",
```

"Вне сети" на английском было бы "Offline". Как вариант, можно ещё сказать "Вне блокчейна"

2024-08-19 20:50 UTC, talentlessguy approved these changes

2024-08-20 07:15 UTC, sugh01 approved these changes

2024-08-20 09:24 UTC, merged