FET-1618 Flash of translation mappings on 404 page
ensdomains/ens-app-v3 pull request #836
Opened 2024-08-28 10:15 UTC by vuongnmdevblock

2024-08-28 14:20 UTC, storywithoutend requested changes

2024-08-28 14:20 UTC, storywithoutend commented on src/components/@atoms/ErrorScreen.tsx
> +    return (
We can just return null (blank page) before the page is ready.

2024-08-29 08:23 UTC, storywithoutend approved these changes

2024-09-11 21:13 UTC, sugh01 approved these changes

2024-09-11 21:14 UTC, merged