Capsule integration final
ensdomains/ens-app-v3 pull request #883
Opened 2024-09-25 02:13 UTC by LeonmanRolls

2024-10-24 04:48 UTC, TateB requested changes

2024-10-24 04:48 UTC, TateB commented on src/components/ConnectButton.tsx
> +
would this be better suited to use with wagmi's `useConnections`?

2024-10-24 04:48 UTC, TateB commented on src/components/ConnectButton.tsx
> +            : null,
if you use `...[isCapsuleConnected ? [...] : []]` you can avoid filtering

2024-10-24 04:48 UTC, TateB commented on src/pages/_app.tsx
> +// prettier-ignore-file
remove

2024-10-24 04:48 UTC, TateB commented on src/utils/query/RainbowKitWithCapsuleProvider.tsx
> +    // accentColor: thorinLightTheme.colors.accent, // requires a hex string color but thorinLightTheme returns a hsl string
fix

2024-10-24 04:48 UTC, TateB commented on src/utils/query/capsuleWallet.ts
> +  xUrl: 'https://twitter.com/ensdomains',
we have these elsewhere i think, would be nice to have a single reference

2024-10-24 04:48 UTC, TateB commented on src/utils/query/capsuleWallet.ts
> +  supportUrl: 'mailto:help@ens.domains',
is this a real email?

2024-10-24 04:48 UTC, TateB commented on src/utils/query/wagmi.ts
> -
we still need these unless they went somewhere else, our logic means we're always defaulting to the 0th item in the chain array (without it it'll stay on the last connected supported chain)

2025-01-22 06:33 UTC, LeonmanRolls commented on src/components/@molecules/TransactionDialogManager/stage/query.ts
> +  const largestMedianGasFee = await getLargestMedianGasFee()
don't need to do this unless it's capsule

2025-01-22 06:40 UTC, LeonmanRolls commented on src/hooks/pages/profile/useRenew/useRenew.test.ts
> +    console.log('hi there')
remove

2025-01-23 04:20 UTC, storywithoutend requested changes
<img width="1247" alt="Screenshot 2025-01-23 at 12 18 16 PM" src="https://github.com/user-attachments/assets/cec3d7ff-1db0-4219-9776-9119ae74c41f" />
When not connected, testnet shows holesky

2025-01-23 05:50 UTC, storywithoutend requested changes
If you log out and log in with capsule, sometimes the <ConnectButton/> will not update to connected.  You have to click connect > sign in with capsule in order for it to trigger login.

2025-01-23 05:50 UTC, storywithoutend commented on src/components/@molecules/TransactionDialogManager/stage/TransactionStageModal.tsx
>  import { queryOptions } from '@tanstack/react-query'
<img width="651" alt="Screenshot 2025-01-23 at 12 42 19 PM" src="https://github.com/user-attachments/assets/3dfbadc0-1b8a-4d23-9cb5-476a4b87ff37" />
Perhaps "Open Wallet" is not the correct wording for a capsule transaction

2025-01-23 13:55 UTC, storywithoutend requested changes

2025-01-23 13:55 UTC, storywithoutend commented on src/utils/query/capsuleWallet.ts
> +  oAuthMethods: [
Is appName supposed to have a value?

2025-01-23 13:55 UTC, storywithoutend commented on src/utils/query/capsuleWallet.ts
> +  iconBackgroundOverride: '#ffffff',
translation for "Sign in with Capsule'?

2025-01-23 13:55 UTC, storywithoutend commented on src/utils/query/capsuleWallet.ts
> +  },
projectId should be WC_PROJECT_ID?

2025-03-13 07:17 UTC, closed without merging