FET-1689: Name Renew Deeplink Params
ensdomains/ens-app-v3 pull request #907
Opened 2024-11-01 09:32 UTC by staslysak

2024-11-19 05:09 UTC, storywithoutend requested changes

2024-11-20 11:57 UTC, storywithoutend requested changes

2024-11-20 11:59 UTC, storywithoutend requested changes

2024-11-20 11:59 UTC, storywithoutend commented on src/utils/string.test.ts
> +import { it, describe, expect } from "vitest";
I added this test file. Use it to test the refactor of parseNumericString so that it fulfils the behaviour I listed in the comment.

2024-12-04 01:44 UTC, LeonmanRolls approved these changes

2024-12-08 20:41 UTC, sugh01 approved these changes

2024-12-09 02:13 UTC, storywithoutend approved these changes

2024-12-09 02:13 UTC, merged